version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_volume:/var/www/feralves/wordpress
    restart: unless-stopped
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WP_HOSTNAME
    depends_on:
      - mariadb
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/feralves/wordpress
    restart: unless-stopped
    networks:
      - inception-network

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mariadb
    restart: unless-stopped
    networks:
      - inception-network

volumes:
  mariadb_volume:
    external: true
  wordpress_volume:
    external: true

networks:
  inception-network:
    driver: bridge