version: "3"

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_volume:/var/www/feralves/wordpress
    restart: unless-stopped
    networks:
      - inception-network

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    environment:
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - wordpress_volume:/var/www/feralves/wordpress
    restart: unless-stopped
    networks:
      - inception-network

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception-network
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_volume:
    external: true
  wordpress_volume:
    external: true

networks:
  inception-network:
    driver: bridge